import { Hero } from '../types';

export const MLBB_HEROES: Hero[] = [
  { id: 1, name: 'Miya', role_primary: 'Marksman' },
  { id: 2, name: 'Balmond', role_primary: 'Fighter' },
  { id: 3, name: 'Saber', role_primary: 'Assassin' },
  { id: 4, name: 'Alice', role_primary: 'Mage', role_secondary: 'Tank' },
  { id: 5, name: 'Nana', role_primary: 'Mage', role_secondary: 'Support' },
  { id: 6, name: 'Tigreal', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 7, name: 'Alucard', role_primary: 'Fighter', role_secondary: 'Assassin' },
  { id: 8, name: 'Karina', role_primary: 'Assassin' },
  { id: 9, name: 'Akai', role_primary: 'Tank' },
  { id: 10, name: 'Franco', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 11, name: 'Bane', role_primary: 'Fighter', role_secondary: 'Mage' },
  { id: 12, name: 'Bruno', role_primary: 'Marksman' },
  { id: 13, name: 'Clint', role_primary: 'Marksman' },
  { id: 14, name: 'Rafaela', role_primary: 'Support' },
  { id: 15, name: 'Eudora', role_primary: 'Mage' },
  { id: 16, name: 'Zilong', role_primary: 'Fighter', role_secondary: 'Assassin' },
  { id: 17, name: 'Fanny', role_primary: 'Assassin' },
  { id: 18, name: 'Layla', role_primary: 'Marksman' },
  { id: 19, name: 'Minotaur', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 20, name: 'Lolita', role_primary: 'Support', role_secondary: 'Tank' },
  { id: 21, name: 'Hayabusa', role_primary: 'Assassin' },
  { id: 22, name: 'Freya', role_primary: 'Fighter' },
  { id: 23, name: 'Gord', role_primary: 'Mage' },
  { id: 24, name: 'Natalia', role_primary: 'Assassin' },
  { id: 25, name: 'Kagura', role_primary: 'Mage' },
  { id: 26, name: 'Chou', role_primary: 'Fighter' },
  { id: 27, name: 'Sun', role_primary: 'Fighter' },
  { id: 28, name: 'Alpha', role_primary: 'Fighter' },
  { id: 29, name: 'Ruby', role_primary: 'Fighter', role_secondary: 'Tank' },
  { id: 30, name: 'Yi Sun-shin', role_primary: 'Assassin', role_secondary: 'Marksman' },
  { id: 31, name: 'Moskov', role_primary: 'Marksman' },
  { id: 32, name: 'Johnson', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 33, name: 'Cyclops', role_primary: 'Mage' },
  { id: 34, name: 'Estes', role_primary: 'Support' },
  { id: 35, name: 'Hilda', role_primary: 'Fighter', role_secondary: 'Tank' },
  { id: 36, name: 'Aurora', role_primary: 'Mage' },
  { id: 37, name: 'Lapu-Lapu', role_primary: 'Fighter' },
  { id: 38, name: 'Vexana', role_primary: 'Mage' },
  { id: 39, name: 'Roger', role_primary: 'Fighter', role_secondary: 'Marksman' },
  { id: 40, name: 'Karrie', role_primary: 'Marksman' },
  { id: 41, name: 'Gatotkaca', role_primary: 'Tank', role_secondary: 'Fighter' },
  { id: 42, name: 'Harley', role_primary: 'Mage', role_secondary: 'Assassin' },
  { id: 43, name: 'Irithel', role_primary: 'Marksman' },
  { id: 44, name: 'Grock', role_primary: 'Tank', role_secondary: 'Fighter' },
  { id: 45, name: 'Argus', role_primary: 'Fighter' },
  { id: 46, name: 'Odette', role_primary: 'Mage' },
  { id: 47, name: 'Lancelot', role_primary: 'Assassin' },
  { id: 48, name: 'Diggie', role_primary: 'Support' },
  { id: 49, name: 'Hylos', role_primary: 'Tank' },
  { id: 50, name: 'Zhask', role_primary: 'Mage' },
  { id: 51, name: 'Helcurt', role_primary: 'Assassin' },
  { id: 52, name: 'Pharsa', role_primary: 'Mage' },
  { id: 53, name: 'Lesley', role_primary: 'Marksman', role_secondary: 'Assassin' },
  { id: 54, name: 'Jawhead', role_primary: 'Fighter', role_secondary: 'Tank' },
  { id: 55, name: 'Angela', role_primary: 'Support' },
  { id: 56, name: 'Gusion', role_primary: 'Assassin', role_secondary: 'Mage' },
  { id: 57, name: 'Valir', role_primary: 'Mage' },
  { id: 58, name: 'Martis', role_primary: 'Fighter' },
  { id: 59, name: 'Uranus', role_primary: 'Tank' },
  { id: 60, name: 'Hanabi', role_primary: 'Marksman' },
  { id: 61, name: 'Chang\'e', role_primary: 'Mage' },
  { id: 62, name: 'Kaja', role_primary: 'Support', role_secondary: 'Fighter' },
  { id: 63, name: 'Selena', role_primary: 'Assassin', role_secondary: 'Mage' },
  { id: 64, name: 'Aldous', role_primary: 'Fighter' },
  { id: 65, name: 'Claude', role_primary: 'Marksman' },
  { id: 66, name: 'Vale', role_primary: 'Mage' },
  { id: 67, name: 'Leomord', role_primary: 'Fighter' },
  { id: 68, name: 'Lunox', role_primary: 'Mage' },
  { id: 69, name: 'Hanzo', role_primary: 'Assassin' },
  { id: 70, name: 'Belerick', role_primary: 'Tank' },
  { id: 71, name: 'Kimmy', role_primary: 'Marksman', role_secondary: 'Mage' },
  { id: 72, name: 'Thamuz', role_primary: 'Fighter' },
  { id: 73, name: 'Harith', role_primary: 'Mage' },
  { id: 74, name: 'Minsitthar', role_primary: 'Fighter', role_secondary: 'Support' },
  { id: 75, name: 'Kadita', role_primary: 'Mage', role_secondary: 'Assassin' },
  { id: 76, name: 'Badang', role_primary: 'Fighter' },
  { id: 77, name: 'Guinevere', role_primary: 'Fighter' },
  { id: 78, name: 'Granger', role_primary: 'Marksman' },
  { id: 79, name: 'Khufra', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 80, name: 'Terizla', role_primary: 'Fighter' },
  { id: 81, name: 'X.Borg', role_primary: 'Fighter' },
  { id: 82, name: 'Ling', role_primary: 'Assassin' },
  { id: 83, name: 'Dyrroth', role_primary: 'Fighter' },
  { id: 84, name: 'Lylia', role_primary: 'Mage' },
  { id: 85, name: 'Baxia', role_primary: 'Tank' },
  { id: 86, name: 'Masha', role_primary: 'Fighter', role_secondary: 'Tank' },
  { id: 87, name: 'Wanwan', role_primary: 'Marksman' },
  { id: 88, name: 'Silvanna', role_primary: 'Fighter', role_secondary: 'Mage' },
  { id: 89, name: 'Carmilla', role_primary: 'Support', role_secondary: 'Tank' },
  { id: 90, name: 'Cecilion', role_primary: 'Mage' },
  { id: 91, name: 'Atlas', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 92, name: 'Popol and Kupa', role_primary: 'Marksman' },
  { id: 93, name: 'Yu Zhong', role_primary: 'Fighter' },
  { id: 94, name: 'Luo Yi', role_primary: 'Mage' },
  { id: 95, name: 'Barats', role_primary: 'Tank', role_secondary: 'Fighter' },
  { id: 96, name: 'Brody', role_primary: 'Marksman' },
  { id: 97, name: 'Yve', role_primary: 'Mage' },
  { id: 98, name: 'Beatrix', role_primary: 'Marksman' },
  { id: 99, name: 'Phoveus', role_primary: 'Fighter' },
  { id: 100, name: 'Natan', role_primary: 'Marksman' },
  { id: 101, name: 'Aulus', role_primary: 'Fighter' },
  { id: 102, name: 'Floryn', role_primary: 'Support' },
  { id: 103, name: 'Valentina', role_primary: 'Mage' },
  { id: 104, name: 'Edith', role_primary: 'Tank', role_secondary: 'Marksman' },
  { id: 105, name: 'Yin', role_primary: 'Fighter' },
  { id: 106, name: 'Melissa', role_primary: 'Marksman' },
  { id: 107, name: 'Xavier', role_primary: 'Mage' },
  { id: 108, name: 'Julian', role_primary: 'Mage', role_secondary: 'Fighter' },
  { id: 109, name: 'Fredrinn', role_primary: 'Tank', role_secondary: 'Fighter' },
  { id: 110, name: 'Joy', role_primary: 'Assassin', role_secondary: 'Mage' },
  { id: 111, name: 'Arlott', role_primary: 'Fighter', role_secondary: 'Assassin' },
  { id: 112, name: 'Novaria', role_primary: 'Mage' },
  { id: 113, name: 'Ixia', role_primary: 'Marksman' },
  { id: 114, name: 'Nolan', role_primary: 'Assassin' },
  { id: 115, name: 'Cici', role_primary: 'Fighter' },
  { id: 116, name: 'Chip', role_primary: 'Tank', role_secondary: 'Support' },
  { id: 117, name: 'Zhuxin', role_primary: 'Mage' },
  { id: 118, name: 'Suyou', role_primary: 'Assassin', role_secondary: 'Fighter' },
  { id: 119, name: 'Lukas', role_primary: 'Fighter' },
];
